version: '3.8'
services:
    postgres:
        image: postgres
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=edgify
        ports:
          - '5438:5432'
        volumes: 
          - ./server/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql


