version: '3.8'
services:
    postgres:
        image: postgres
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=edgify
        ports:
          - '5438:5432'
        volumes: 
          - ./server/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    web:
      stdin_open: true
      build:
        context: client
        dockerfile: Dockerfile
      volumes:
        - /node_modules
      ports:
        - '3000:3000'

    server:
      build:
        context: server
        dockerfile: Dockerfile
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_HOST=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=edgify
        - POSTGRES_PORT=5432
      volumes:
        - /node_modules
        - ./server/src:/app/src
      ports:
      - '5000:5000'
      depends_on:
        - "postgres"


